[character]
success_symbol = "[ï˜](bold green)"
error_symbol = "[ï—](bold red)"
vicmd_symbol = "[ï‰–](bold green)"

[git_branch]
symbol = 'ğŸŒ± '
#truncation_length = 4
#truncation_symbol = ''
#ignore_branches = ['master', 'main']

[git_status]
ahead = "ï¢ "
behind = "ï£ "
diverged = "ï„¦ "
renamed = "âœ "
deleted = "ï‘˜ "
staged = "ï˜ "
untracked = "ï™ "

[cmd_duration]
#min_time = 5000
#format = "took [â± ]"

[directory]
truncation_length = 3
truncate_to_repo = true
